export const GET_MAP_INFO_START = "GET_MAP_INFO_START";
export const GET_MAP_INFO_REQUEST = "GET_MAP_INFO_REQUEST";
export const GET_MAP_INFO_SUCCESS = "GET_MAP_INFO_SUCCESS";
export const GET_MAP_INFO_FAILED = "GET_MAP_INFO_FAILED";
export const GET_MAP_INFO_FINISHED = "GET_MAP_INFO_FINISHED";

export const UPDATE_COORDINATES = "UPDATE_COORDINATES";

export enum GetMapActionTypes {
  GET_MAP_INFO_START,
  GET_MAP_INFO_REQUEST,
  GET_MAP_INFO_SUCCESS,
  GET_MAP_INFO_FAILED,
  GET_MAP_INFO_FINISHED,
  UPDATE_COORDINATES,
}
